name: Deployment_Simulation

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Print the path of the project
      run: pwd

    - name: Go to project folder
      run: cd /home/runner/work/backend-challenge/backend-challenge

    - name: Print directory contents
      run: ls -l

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Quarkus tests
      run: mvn -B test --file pom.xml
