name: Deployment_Simulation

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Print the path of the project
      run: pwd

    - name: Clone the project
      run: |
        rm -rf backend-challenge/
        git clone https://github.com/npalleta/backend-challenge.git

    - name: Check Maven Version
      run: mvn -version
